MODEL:
  META_ARCHITECTURE: "VQVAEModel"
  INIT_TYPE: "xavier_uniform"
  ENCODER:
    NAME: "ResEncoder"
    N_LAYERS: 2
    NF: 256
    OUT_CHANNELS: 256
    RES_CHANNELS: 128
  GENERATOR:
    NAME: "ResDecoder"
    N_LAYERS: 2
    IN_CHANNELS: 256
    RES_CHANNELS: 128
    NF: 256
  CODEBOOK:
    SIZE: 512
    DIM: 256
    EMA: True
SOLVER:
  IMS_PER_BATCH: 32
  MAX_ITER: 500000
  LR_G: 0.0003
  LR_SCHEDULER_NAME: "Identity"
  CHECKPOINT_PERIOD: 50000
VERSION: 1
SEED: 29871897