_BASE_: "Base-VQVAE.yaml"
INPUT:
  FORMAT: "RGB"
  N_FRAMES_PER_VIDEO_TRAIN: 1
  N_FRAMES_PER_VIDEO_TEST: 16
MODEL:
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  ENCODER:
    NORM: ""
    N_LAYERS: 4
    IN_CHANNELS: 3
  GENERATOR:
    NORM: ""
    N_LAYERS: 4
    OUT_CHANNELS: 3
    OUT_ACTIVATION: "tanh"
  CODEBOOK:
    NUM: 4
    SIZE: 512
SOLVER:
  MAX_ITER: 1000000
  CHECKPOINT_PERIOD: 1000000
TEST:
  EVALUATORS: "MSEEvaluator,CodesExtractor"
DATASETS:
  TRAIN: ("kinetics_train_seq",)
  TEST: ("kinetics_test_seq",)